ROWS = 10
COLS = 9
SQUARE_SIZE = 20.0

CALIB_IMAGE_DIR = "calib_images"
IMAGE_EXTENSION = "*.jpg"

CAMERA_ID = 2
FRAME_WIDTH = 1280
FRAME_HEIGHT = 720
PIXEL_FORMAT = "MJPG"

CALIB_FILE = "camera_params.json"

CORNER_WINDOW = (11, 11)
ZERO_ZONE = (-1, -1)

CRITERIA_MAX_ITER = 30
CRITERIA_EPS = 0.001
